[017] Adiciona actions faltantes em teams e stages controllers
mersonff/clicksign-hackaton pull request #24
Opened 2022-10-29 14:31 UTC by wandesonpaiva

2022-10-31 13:08 UTC, Hugo-NF approved these changes

2022-11-01 00:08 UTC, mersonff approved these changes

2022-11-01 00:25 UTC, Hugo-NF requested changes
Coloca essas respostas de sucesso para retornar usando os jbuilders, da mesma forma que o Emerson fez, para mantermos um padrão

2022-11-04 18:07 UTC, Hugo-NF approved these changes

2022-11-04 21:30 UTC, merged